"""
Triage decision models.
"""

from typing import Literal

from pydantic import BaseModel, Field


class TriagedDecision(BaseModel):
    """
    Triage recommendation for how to handle an invitation.

    Generated by the decision agent based on invitation details,
    minister's priorities, and calendar availability.
    """

    email_id: str = Field(
        description="Email ID linking back to the original invitation"
    )

    decision: Literal["accept", "decline", "delegate", "request_more_info", "defer"] = (
        Field(description="Recommended action for this invitation")
    )

    priority: Literal["high", "medium", "low"] = Field(
        description="Priority level of this invitation for the minister"
    )

    reason: str = Field(
        description="Short explanation for the decision (1-2 sentences)"
    )

    draft_response: str = Field(
        description="Draft email response ready to send or adapt"
    )

    affected_events: list[str] = Field(
        default_factory=list,
        description="Titles of calendar events that conflict or are relevant to this decision",
    )
