"""
Triage decision models.
"""

from typing import Literal

from pydantic import BaseModel, Field


class TriagedDecision(BaseModel):
    """
    Triage recommendation for how to handle an invitation.

    Generated by the decision agent based on invitation details,
    minister's priorities, and calendar availability.
    """
    title: str = Field(description="Name of the event")

    document_id: str = Field(description="Document ID linking back to the source document")

    minister_decision: Literal["accept", "decline"] = Field(
        description="Recommended action for this invitation"
    )

    priority: Literal["high", "medium", "low"] = Field(description="Priority level of this invitation for the minister")

    reason: str = Field(
        min_length=10,
        description="Short explanation for the decision (1-2 sentences)",
    )

    draft_response: str = Field(min_length=20, description="Draft email response ready to send or adapt")

    affected_events: list[str] = Field(
        default_factory=list,
        description="Titles of calendar events that conflict or are relevant to this decision",
    )
